// <auto-generated />
using System;
using GranjaLosAres_API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GranjaLosAres_API.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20240916054348_AddRefreshTokensOnly")]
    partial class AddRefreshTokensOnly
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GranjaLosAres_API.Models.ClasificacionHuevo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cajas")
                        .HasColumnType("int");

                    b.Property<int>("CartonesExtras")
                        .HasColumnType("int");

                    b.Property<bool?>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaClaS")
                        .HasColumnType("datetime");

                    b.Property<int>("HuevosSueltos")
                        .HasColumnType("int");

                    b.Property<int>("IdProd")
                        .HasColumnType("int");

                    b.Property<string>("Tamano")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<int?>("TotalUnitaria")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("int")
                        .HasComputedColumnSql("([dbo].[CalcularCantidadTotalUnitaria]([Cajas],[CartonesExtras],[HuevosSueltos]))", false);

                    b.HasKey("Id")
                        .HasName("PK__Clasific__3214EC27BBDCC8F0");

                    b.HasIndex("IdProd");

                    b.ToTable("ClasificacionHuevos");
                });

            modelBuilder.Entity("GranjaLosAres_API.Models.Cliente", b =>
                {
                    b.Property<int>("ClienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ClienteID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClienteId"));

                    b.Property<string>("Direccion")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<bool?>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("NombreCliente")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("ClienteId")
                        .HasName("PK__Clientes__71ABD0A7E7862C51");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("GranjaLosAres_API.Models.Corral", b =>
                {
                    b.Property<int>("IdCorral")
                        .HasColumnType("int");

                    b.Property<bool>("Agua")
                        .HasColumnType("bit");

                    b.Property<double>("Alto")
                        .HasColumnType("float");

                    b.Property<double>("Ancho")
                        .HasColumnType("float");

                    b.Property<int>("Bebederos")
                        .HasColumnType("int");

                    b.Property<int>("Capacidad")
                        .HasColumnType("int");

                    b.Property<int>("Comederos")
                        .HasColumnType("int");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<double>("Largo")
                        .HasColumnType("float");

                    b.Property<string>("NumCorral")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Ponederos")
                        .HasColumnType("int");

                    b.HasKey("IdCorral");

                    b.ToTable("Corral", (string)null);
                });

            modelBuilder.Entity("GranjaLosAres_API.Models.DetallesVentum", b =>
                {
                    b.Property<int>("DetalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DetalleID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DetalleId"));

                    b.Property<int?>("CantidadVendida")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<bool?>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<decimal?>("PrecioUnitario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10, 2)")
                        .HasDefaultValue(0m);

                    b.Property<int?>("ProductoId")
                        .HasColumnType("int")
                        .HasColumnName("ProductoID");

                    b.Property<string>("TamanoHuevo")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("TipoEmpaque")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal?>("Total")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(21, 2)")
                        .HasComputedColumnSql("([CantidadVendida]*[PrecioUnitario])", true);

                    b.Property<int?>("TotalHuevos")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("int")
                        .HasComputedColumnSql("(case when [TipoEmpaque]='Caja' then [CantidadVendida]*(360) when [TipoEmpaque]='Cartón' then [CantidadVendida]*(30) else [CantidadVendida] end)", true);

                    b.Property<int?>("VentaId")
                        .HasColumnType("int")
                        .HasColumnName("VentaID");

                    b.HasKey("DetalleId")
                        .HasName("PK__Detalles__6E19D6FA2008A5B1");

                    b.HasIndex("ProductoId");

                    b.HasIndex("VentaId");

                    b.ToTable("DetallesVenta");
                });

            modelBuilder.Entity("GranjaLosAres_API.Models.EstadoLote", b =>
                {
                    b.Property<int>("IdEstado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id_Estado");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEstado"));

                    b.Property<int>("Bajas")
                        .HasColumnType("int");

                    b.Property<int>("CantidadG")
                        .HasColumnType("int")
                        .HasColumnName("Cantidad_G");

                    b.Property<bool?>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime")
                        .HasColumnName("Fecha_Registro");

                    b.Property<int>("IdEtapa")
                        .HasColumnType("int")
                        .HasColumnName("Id_Etapa");

                    b.Property<int>("IdLote")
                        .HasColumnType("int");

                    b.Property<int?>("Semana")
                        .HasColumnType("int");

                    b.HasKey("IdEstado")
                        .HasName("PK_EstadoLote_G");

                    b.HasIndex("IdEtapa");

                    b.HasIndex("IdLote");

                    b.ToTable("EstadoLote", (string)null);
                });

            modelBuilder.Entity("GranjaLosAres_API.Models.Etapa", b =>
                {
                    b.Property<int>("IdEtapa")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdEtapa");

                    b.ToTable("Etapas");
                });

            modelBuilder.Entity("GranjaLosAres_API.Models.Lote", b =>
                {
                    b.Property<int>("IdLote")
                        .HasColumnType("int");

                    b.Property<int>("CantidadG")
                        .HasColumnType("int");

                    b.Property<int?>("CantidadGctual")
                        .HasColumnType("int");

                    b.Property<bool?>("Estado")
                        .HasColumnType("bit");

                    b.Property<bool>("EstadoBaja")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaAdq")
                        .HasColumnType("datetime");

                    b.Property<int>("IdCorral")
                        .HasColumnType("int");

                    b.Property<int>("IdRaza")
                        .HasColumnType("int");

                    b.Property<string>("NumLote")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.HasKey("IdLote")
                        .HasName("PK_Table1");

                    b.HasIndex("IdCorral");

                    b.HasIndex("IdRaza");

                    b.ToTable("Lote", (string)null);
                });

            modelBuilder.Entity("GranjaLosAres_API.Models.ProduccionGallina", b =>
                {
                    b.Property<int>("IdProd")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProd"));

                    b.Property<int>("CantCajas")
                        .HasColumnType("int");

                    b.Property<int>("CantCartones")
                        .HasColumnType("int");

                    b.Property<int>("CantSueltos")
                        .HasColumnType("int");

                    b.Property<int?>("CantTotal")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("int")
                        .HasComputedColumnSql("([dbo].[CalcularCantidadTotalProduccion]([CantCajas],[CantCartones],[CantSueltos]))", false);

                    b.Property<int?>("Defectuosos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<bool?>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaRegistroP")
                        .HasColumnType("datetime");

                    b.Property<int>("IdLote")
                        .HasColumnType("int");

                    b.HasKey("IdProd")
                        .HasName("PK__Producci__E40D971DC3C087DC");

                    b.HasIndex("IdLote");

                    b.ToTable("ProduccionGallinas");
                });

            modelBuilder.Entity("GranjaLosAres_API.Models.Producto", b =>
                {
                    b.Property<int>("ProductoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ProductoID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductoId"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<bool?>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("NombreProducto")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("ProductoId")
                        .HasName("PK__Producto__A430AE83E9DF4B6A");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("GranjaLosAres_API.Models.RazaGallina", b =>
                {
                    b.Property<int>("IdRaza")
                        .HasColumnType("int");

                    b.Property<string>("CaractEspec")
                        .HasMaxLength(5000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5000)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(90)
                        .IsUnicode(false)
                        .HasColumnType("varchar(90)");

                    b.Property<string>("ColorH")
                        .IsRequired()
                        .HasMaxLength(90)
                        .IsUnicode(false)
                        .HasColumnType("varchar(90)");

                    b.Property<bool?>("Estado")
                        .HasColumnType("bit");

                    b.Property<string>("Origen")
                        .IsRequired()
                        .HasMaxLength(90)
                        .IsUnicode(false)
                        .HasColumnType("varchar(90)");

                    b.Property<string>("Raza")
                        .IsRequired()
                        .HasMaxLength(90)
                        .IsUnicode(false)
                        .HasColumnType("varchar(90)");

                    b.HasKey("IdRaza");

                    b.ToTable("RazaGallina", (string)null);
                });

            modelBuilder.Entity("GranjaLosAres_API.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__Roles__3214EC071BC0321D");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("GranjaLosAres_API.Models.StockHuevo", b =>
                {
                    b.Property<string>("Tamano")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Cajas")
                        .HasColumnType("int");

                    b.Property<int>("CartonesExtras")
                        .HasColumnType("int");

                    b.Property<int>("HuevosSueltos")
                        .HasColumnType("int");

                    b.HasKey("Tamano")
                        .HasName("PK__StockHue__799ADF87B8CE711C");

                    b.ToTable("StockHuevos", t =>
                        {
                            t.HasTrigger("trg_ResetStockHuevos");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("GranjaLosAres_API.Models.TriggerDebugLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("NewCartonesExtras")
                        .HasColumnType("int");

                    b.Property<int?>("OldCartonesExtras")
                        .HasColumnType("int");

                    b.Property<string>("OperationType")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.ToTable("TriggerDebugLog", (string)null);
                });

            modelBuilder.Entity("GranjaLosAres_API.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("FechaDeRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("NombreUser")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Usuarios__3214EC07059D3025");

                    b.HasIndex("RoleId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("GranjaLosAres_API.Models.Venta", b =>
                {
                    b.Property<int>("VentaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("VentaID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VentaId"));

                    b.Property<int?>("ClienteId")
                        .HasColumnType("int")
                        .HasColumnName("ClienteID");

                    b.Property<bool?>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateOnly>("FechaVenta")
                        .HasColumnType("date");

                    b.Property<decimal?>("TotalVenta")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("VentaId")
                        .HasName("PK__Ventas__5B41514CA5140F29");

                    b.HasIndex("ClienteId");

                    b.ToTable("Ventas");
                });

            modelBuilder.Entity("GranjaLosAres_API.Models.VistaClasificacionHuevo", b =>
                {
                    b.Property<int>("Cajas")
                        .HasColumnType("int");

                    b.Property<int?>("CajasRestantes")
                        .HasColumnType("int");

                    b.Property<int?>("CantidadTotalClasificada")
                        .HasColumnType("int");

                    b.Property<int?>("CantidadTotalProduccion")
                        .HasColumnType("int");

                    b.Property<int>("CartonesExtras")
                        .HasColumnType("int");

                    b.Property<int?>("CartonesRestantes")
                        .HasColumnType("int");

                    b.Property<int>("HuevosSueltos")
                        .HasColumnType("int");

                    b.Property<int?>("HuevosSueltosRestantes")
                        .HasColumnType("int");

                    b.Property<int>("IdProduccion")
                        .HasColumnType("int");

                    b.Property<int?>("StockRestante")
                        .HasColumnType("int");

                    b.Property<string>("Tamaño")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.ToTable((string)null);

                    b.ToView("VistaClasificacionHuevos", (string)null);
                });

            modelBuilder.Entity("GranjaLosAres_API.Models.VistaDashboard", b =>
                {
                    b.Property<int>("Bajas")
                        .HasColumnType("int");

                    b.Property<int>("CantidadGallinas")
                        .HasColumnType("int");

                    b.Property<int?>("CantidadGallinasActual")
                        .HasColumnType("int");

                    b.Property<int>("IdLote")
                        .HasColumnType("int");

                    b.Property<int>("ProduccionTotal")
                        .HasColumnType("int");

                    b.Property<string>("Raza")
                        .HasMaxLength(90)
                        .IsUnicode(false)
                        .HasColumnType("varchar(90)");

                    b.ToTable((string)null);

                    b.ToView("VistaDashboard", (string)null);
                });

            modelBuilder.Entity("GranjaLosAres_API.Models.VistaStockRestanteHuevo", b =>
                {
                    b.Property<int?>("CajasRestantes")
                        .HasColumnType("int");

                    b.Property<int?>("CantidadTotalProduccion")
                        .HasColumnType("int");

                    b.Property<int?>("CartonesRestantes")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaProdu")
                        .HasColumnType("datetime");

                    b.Property<int?>("HuevosSueltosRestantes")
                        .HasColumnType("int");

                    b.Property<int>("IdLote")
                        .HasColumnType("int");

                    b.Property<int>("IdProduccion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("StockRestante")
                        .HasColumnType("int");

                    b.ToTable((string)null);

                    b.ToView("VistaStockRestanteHuevos", (string)null);
                });

            modelBuilder.Entity("RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Expiration")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsRevoked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__RefreshToken__3214EC07");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("GranjaLosAres_API.Models.ClasificacionHuevo", b =>
                {
                    b.HasOne("GranjaLosAres_API.Models.ProduccionGallina", "IdProdNavigation")
                        .WithMany("ClasificacionHuevos")
                        .HasForeignKey("IdProd")
                        .IsRequired()
                        .HasConstraintName("FK_ClasificacionHuevos_ProduccionGallinas");

                    b.Navigation("IdProdNavigation");
                });

            modelBuilder.Entity("GranjaLosAres_API.Models.DetallesVentum", b =>
                {
                    b.HasOne("GranjaLosAres_API.Models.Producto", "Producto")
                        .WithMany("DetallesVenta")
                        .HasForeignKey("ProductoId")
                        .HasConstraintName("FK__DetallesV__Produ__59FA5E80");

                    b.HasOne("GranjaLosAres_API.Models.Venta", "Venta")
                        .WithMany("DetallesVenta")
                        .HasForeignKey("VentaId")
                        .HasConstraintName("FK__DetallesV__Venta__5BE2A6F2");

                    b.Navigation("Producto");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("GranjaLosAres_API.Models.EstadoLote", b =>
                {
                    b.HasOne("GranjaLosAres_API.Models.Etapa", "IdEtapaNavigation")
                        .WithMany("EstadoLotes")
                        .HasForeignKey("IdEtapa")
                        .IsRequired()
                        .HasConstraintName("FK_EstadoLote_Etapas");

                    b.HasOne("GranjaLosAres_API.Models.Lote", "IdLoteNavigation")
                        .WithMany("EstadoLotes")
                        .HasForeignKey("IdLote")
                        .IsRequired()
                        .HasConstraintName("FK_EstadoLote_Lote");

                    b.Navigation("IdEtapaNavigation");

                    b.Navigation("IdLoteNavigation");
                });

            modelBuilder.Entity("GranjaLosAres_API.Models.Lote", b =>
                {
                    b.HasOne("GranjaLosAres_API.Models.Corral", "IdCorralNavigation")
                        .WithMany("Lotes")
                        .HasForeignKey("IdCorral")
                        .IsRequired()
                        .HasConstraintName("FK_Table1_Corral");

                    b.HasOne("GranjaLosAres_API.Models.RazaGallina", "IdRazaNavigation")
                        .WithMany("Lotes")
                        .HasForeignKey("IdRaza")
                        .IsRequired()
                        .HasConstraintName("FK_Table1_RazaGallina");

                    b.Navigation("IdCorralNavigation");

                    b.Navigation("IdRazaNavigation");
                });

            modelBuilder.Entity("GranjaLosAres_API.Models.ProduccionGallina", b =>
                {
                    b.HasOne("GranjaLosAres_API.Models.Lote", "IdLoteNavigation")
                        .WithMany("ProduccionGallinas")
                        .HasForeignKey("IdLote")
                        .IsRequired()
                        .HasConstraintName("FK_ProduccionGallinas_Lote");

                    b.Navigation("IdLoteNavigation");
                });

            modelBuilder.Entity("GranjaLosAres_API.Models.Usuario", b =>
                {
                    b.HasOne("GranjaLosAres_API.Models.Role", "Role")
                        .WithMany("Usuarios")
                        .HasForeignKey("RoleId")
                        .HasConstraintName("FK__Usuarios__RoleId__628FA481");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("GranjaLosAres_API.Models.Venta", b =>
                {
                    b.HasOne("GranjaLosAres_API.Models.Cliente", "Cliente")
                        .WithMany("Venta")
                        .HasForeignKey("ClienteId")
                        .HasConstraintName("FK__Ventas__ClienteI__6477ECF3");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("RefreshToken", b =>
                {
                    b.HasOne("GranjaLosAres_API.Models.Usuario", "Usuario")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_RefreshToken_Usuario");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("GranjaLosAres_API.Models.Cliente", b =>
                {
                    b.Navigation("Venta");
                });

            modelBuilder.Entity("GranjaLosAres_API.Models.Corral", b =>
                {
                    b.Navigation("Lotes");
                });

            modelBuilder.Entity("GranjaLosAres_API.Models.Etapa", b =>
                {
                    b.Navigation("EstadoLotes");
                });

            modelBuilder.Entity("GranjaLosAres_API.Models.Lote", b =>
                {
                    b.Navigation("EstadoLotes");

                    b.Navigation("ProduccionGallinas");
                });

            modelBuilder.Entity("GranjaLosAres_API.Models.ProduccionGallina", b =>
                {
                    b.Navigation("ClasificacionHuevos");
                });

            modelBuilder.Entity("GranjaLosAres_API.Models.Producto", b =>
                {
                    b.Navigation("DetallesVenta");
                });

            modelBuilder.Entity("GranjaLosAres_API.Models.RazaGallina", b =>
                {
                    b.Navigation("Lotes");
                });

            modelBuilder.Entity("GranjaLosAres_API.Models.Role", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("GranjaLosAres_API.Models.Usuario", b =>
                {
                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("GranjaLosAres_API.Models.Venta", b =>
                {
                    b.Navigation("DetallesVenta");
                });
#pragma warning restore 612, 618
        }
    }
}
